# Site settings
title: Daniel Shiffman
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learn Creative Code. Daniel Shiffman works as an Associate Arts Professor at the Interactive Telecommunications Program at NYU’s Tisch School of the Arts.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shiffman.net" # the base hostname & protocol for your site
twitter_username: shiffman
github_username:  shiffman
permalink: pretty

# Build settings
markdown: kramdown

exclude: 
  - archived
  - shiffmanv2
